### ISSUE TITLE
Please publish new version on npm

### ISSUE THREAD

**Issue by YannBergonzat** [Microclimat/generator-happy#1]
Hey @Jibbarth , I just fixed the sync-vm task. You stupidely forgot the slash after the ${MountedFolder} and it is very important. 

Can you publish the fix quickly on npm? 

Best regards :+1:

**Comment by Jibbarth** [comment]
Hey @YannBergonzat,

I just did it [here](https://github.com/Microclimat/generator-happy/releases/tag/v1.0.4)

Thanks for your participation :smile:
